I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    return scene1
  File "game/script.rpy", line 22, in <module>
    return scene1
NameError: name 'scene1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script
    return scene1
  File "C:\Users\3loyK\RenPy\renpy-8.3.2-sdk\renpy\ast.py", line 1479, in execute
    renpy.store._return = renpy.python.py_eval(self.expression)
  File "C:\Users\3loyK\RenPy\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\3loyK\RenPy\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 22, in <module>
    return scene1
NameError: name 'scene1' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
MyFirstGame 1.0
Thu Sep 26 23:55:59 2024
